dist: trusty
language: php
sudo: required
branches:
  only:
  - sdk
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
before_install:
install:
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-4.8.36.phar
script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/OSTSdkTest.php
after_script: