dist: trusty
language: php
sudo: required
branches:
  only:
  - sdk
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
php:
  - 5.5
before_install:
install:
before_script:
  - composer update
script:
  - phpunit --bootstrap vendor/autoload.php tests/OSTSdkTest.php
after_script:
